### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest-mods/3d_armor#10]
* [x] Switch to markdown
* [x] add screenshot to readme

**Comment by sirrobzeroone** [comment]
Let me know if its the readme under 3d_armor that needs moving/updating to markdown, happy to make that change and add that doco about the inventories being a "detached inventory".

Rob

**Comment by BuckarooBanzay** [comment]
> Let me know if its the readme under 3d_armor that needs moving/updating to markdown, happy to make that change and add that doco about the inventories being a "detached inventory".
> 
> Rob

I think i meant this readme back then:
https://github.com/minetest-mods/3d_armor/blob/master/3d_armor/README.txt

Its still a textfile and i think it can be considered an "api-documentation". So: yeah, the detached inventory stuff should fit in there :+1:

**Comment by sirrobzeroone** [comment]
I have a draft of the armor3d>>Readme.MD, not done yet as I need to finish sorting callbacks and I might split the contents section into 3 columns not 2 columns. But let me know if this is on the right track, did my best to trackdown info from the 3darmor forum thread or straight out of the code. I also added a credits section at the end.

Draft: https://github.com/sirrobzeroone/3d_armor/blob/master/3d_armor/README.MD

**Comment by BuckarooBanzay** [comment]
> I have a draft of the armor3d>>Readme.MD, not done yet as I need to finish sorting callbacks and need to add some examples and figure out how to explain physics :). I might split the contents section into 3 columns not 2 columns.

Oh, shiny :sparkles: 

> But let me know if this is on the right track, did my best to trackdown info from the 3darmor forum thread or straight out of the code. I also added a credits section at the end.

Looks good from a first glance, the TOC on the top is really helpful :+1:

**Comment by BuckarooBanzay** [comment]
fixed by #26 (thanks @sirrobzeroone)
