### ISSUE TITLE
Does the move to split the armor types break backward compatiblity?

### ISSUE THREAD

**Issue by dacmot** [minetest-mods/3d_armor#117]
We had frozen 3d_armor in [WhyNot?](https://github.com/minetest-whynot/whynot-game) just before the armor types got split.

Before we [move to the latest](https://github.com/minetest-whynot/whynot-game/issues/133), are you aware of any issues with it? In particular, does it cause any kind of problems with existing worlds?

In the PR, SmallJoker had mentioned a possible issue with existing servers. Would that be a problem if the modpack is part of a game like WhyNot, and the server gets updated and restarted?

Thanks!

**Comment by BuckarooBanzay** [comment]
> are you aware of any issues with it? In particular, does it cause any kind of problems with existing worlds?

been using that myself on 2 servers ([pandorabox](https://github.com/pandorabox-io/pandorabox-mods/) and [bananaland](https://github.com/banananaland/bananaland-mods)) and didn't have any issues migrating (there are automated tests that would catch such issues anyway)

> Moreover, we might want to wait a bit if they are going to split the shields as well.

If it were up to me i would separate those parts out into separate _mods_ entirely (with separate git-repos) but i haven't found the time and energy yet to start that discussion :)

**Comment by dacmot** [comment]
Thanks! I think we can take a closer look at merging this soon. If it ever comes to being split into separate mods, we'll revisit then.

I can understand splitting the API from the armors themselves, but just out of curiosity, what kind of benefits do you see from splitting each armor type into its own mod/repository? Seems to me like a lot of work, which would incidentally generate more work in the future.

As a side note, a few years ago I inherited the armor_addon (now moarmours) set. If you've got some ideas for it, let me know!

**Comment by Lazerbeak12345** [comment]
It might decrease dependency on MTG to separate them like so. That's the only thing I can think of.

**Comment by BuckarooBanzay** [comment]
> but just out of curiosity, what kind of benefits do you see from splitting each armor type into its own mod/repository?

mostly the ability to selectively pull in different armors and leave others out, both on the server-operator side (with git) and on the client-side (with content-db)
And yes: i'm aware that you can disable mods in a modpack but i never really got warm with that :shrug: 

I just really like the separation of core/api and plugins

(closing this, if you have further questions feel free to continue or ping me up on irc/discord :+1: )
