### ISSUE TITLE
[Question] About the use of detached inventories

### ISSUE THREAD

**Issue by hlqkj** [minetest-mods/3d_armor#126]
Why are they used in the first place?

Am I correct in assuming that this is just a legacy from the past, when we didn't have player inventory callbacks (that is, before https://github.com/minetest/minetest/pull/7185) or are there other reasons requiring them?

**Comment by BuckarooBanzay** [comment]
> Why are they used in the first place?

> Am I correct in assuming that this is just a legacy from the past

Highly likely, yes. If you have improvements feel free to open a PR :+1:
