### ISSUE TITLE
Armor still damageable in (pvp) protected arear

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest-mods/3d_armor#13]
Reported by `bosapara` in the forums:
```
Even in protect, player's armor can be damaged / crashed by another player.
How to reproduce a bug: just punch protected player, his armor will crash more and more.
Checked this bug on Pandora - the same. Tried to fix it, but failed unfortunately.
```

**EDIT**: possible fix by the same author (untested, just copy-pasta'd from the forums):

```lua
if armor.config.punch_damage == true then
	minetest.register_on_punchplayer(function(player, hitter,
			time_from_last_punch, tool_capabilities)
		local name = player:get_player_name()
		local name2 = hitter:get_player_name()		

		if name and name2 and minetest.is_protected(player:get_pos(), "") then

			return

		elseif name then

			armor:punch(player, hitter, time_from_last_punch, tool_capabilities)
			last_punch_time[name] = minetest.get_gametime()

		end	

	end)
end
```

**Comment by johalun** [comment]
Is this related to my dying of fall damage even though damage is disabled on the server? If I disable this mod, I don't take damage.

**Comment by BuckarooBanzay** [comment]
> Is this related to my dying of fall damage even though damage is disabled on the server? If I disable this mod, I don't take damage.

I don't think thats the same issue, can you open a new issue with the details if possible? (Mods, engine, how to reproduce)

**Comment by sirrobzeroone** [comment]
I did some initial testing on this fix, using "protector redo" (https://notabug.org/TenPlus1/protector):

The code above added
- PVP configured on (false), player, armor and attacking weapon all recieved damage as expected.
- PVP configured off (true), player, armor and attacking weapon recieved no damage as expected.

I'll do an entity test as well but given how the codes written not expecting that to fail.
