### ISSUE TITLE
Minetest shutsdown game

### ISSUE THREAD

**Issue by AyeGeeToo** [minetest-mods/3d_armor#135]
Hi,
I can create and play a game for a while and close it but when I try to play the game again Minetest shuts it down with the following message:
            AsyncErr: Lua: Runtime error from mod '' in callback on_joinplayer(): (load):1578: attempt to index field 'items_progress' (a nil value)
            Stack traceback:
                (load):1578: in function 'get_items_fs'
                (load):1774: in function 'make_fs'
                (load):177: in function: 'func'
                /home/USR/.minetest/mods/3d_armor/3d_armor/api.lua:340: in function 'run_callbacks'
                /home/USR/.minetest/mods/3d_armor/3d_armor/api.lua:361: in function 'update_player_visuals'
                /home/USR/.minetest/mods/3d_armor/3d_armor/api.lua:528: in function 'set_player_armor'
                /home/USR/.minetest/mods/3d_armor/3d_armor/init.lua:285: in function 'init_player_armor'
                /home/USR/.minetest/mods/3d_armor/3d_armor/init.lua:326: in function <home/USR/.minetest/mods/3d_armor/3d_armor/init.lua:324>
                /usr/share/minetest/builtin/common/register.lua:26 in function </usr/share/minetest/builtin/common/register.lua:12>

I did try to disable this mod and load the game however that caused Minetest to shutdown.

[Edit] Currently running Minetest 5.8.0 on Linux Mint 21.2

**Comment by BuckarooBanzay** [comment]
```
Stack traceback:
(load):1578: in function 'get_items_fs'
(load):1774: in function 'make_fs'
(load):177: in function: 'func'
/home/USR/.minetest/mods/3d_armor/3d_armor/api.lua:340: in function 'run_callbacks'
```
That ^ part of the stacktrace is pretty weird, are you on the latest version of the mod?
What other mods are you using besides this one?

Also: is it possible to pack up your world (and maybe the mods-) folder and post it here?

> I did try to disable this mod and load the game however that caused Minetest to shutdown.

Do i understand this correctly: the engine still crashes _after_ you disabled the mod?

**Comment by AyeGeeToo** [comment]
> ```
> Stack traceback:
> (load):1578: in function 'get_items_fs'
> (load):1774: in function 'make_fs'
> (load):177: in function: 'func'
> /home/USR/.minetest/mods/3d_armor/3d_armor/api.lua:340: in function 'run_callbacks'
> ```
> 
> That ^ part of the stacktrace is pretty weird, are you on the latest version of the mod? What other mods are you using besides this one?

I substituted USR for the username when typing the error out simply to help me get my head around this.
All mods were up to date at the time.
 
> Also: is it possible to pack up your world (and maybe the mods-) folder and post it here?

I will give you a list of the active mods as well as the world and mods folder when I have a bit more time a couple of days.

> > I did try to disable this mod and load the game however that caused Minetest to shutdown.
> 
> Do i understand this correctly: the engine still crashes _after_ you disabled the mod?

Being relatively inexperienced with Linux & Minetest I wasn't brave enough to retry but Minetest did shut down after trying to load the game with the mod disabled. Shortly after Mint crashed and required a hard reset.

Had a boot issue today, entered recovery mode and continued to boot Mint from there. 
I read your response and ran Minetest forgaetting about the grahic driver warning. From here I was able load the game with the mod disabled.
After rebooting the system Minetest did not load the game with the mod disabled and gave me the following message:
            AsyncErr: Lua: Runtime error from mod '' in callback environment_Step(): (load):1578: attempt to index field 'items_progress' (a nil value)
            Stack traceback:
                (load):1578: in function 'get_items_fs'
                (load):1774: in function 'make_fs'
                (load):177: in function: 'func'
                /usr/share/minetest/builtin/common/after.lua:20 in function </usr/share/minetest/builtin/common/after.lua:5>
                /usr/share/minetest/builtin/common/register.lua:26 in function </usr/share/minetest/builtin/common/register.lua:12>

**Comment by AyeGeeToo** [comment]
[World Kactus Jack Too.tar.gz](https://github.com/minetest-mods/3d_armor/files/14548374/World.Kactus.Jack.Too.tar.gz)
[Game Mod Status - KactusJackToo.odt](https://github.com/minetest-mods/3d_armor/files/14548389/Game.Mod.Status.-.KactusJackToo.odt)


This is the world I was trying to test when Minetest shutdown. I've done further testing, Minetest has not shutdown again and I've been able to play in the world with the mod disabled. Still won't load with the mod enabled.

Unable to upload the mods folder due to size limits so attached is a list of which mods and whether they were enabled when the game was created.

**Comment by BuckarooBanzay** [comment]
@AyeGeeToo looks like this is an `i3` issue: https://github.com/mt-historical/i3/issues/7#issuecomment-1987050539

can you take a look  there and let me know if that fixes it? (ping me up if you need help or something)

(thanks @wsor4035)

**Comment by AyeGeeToo** [comment]
@BuckarooBanzay that code change worked, thankyou. 
Also thankyou to @wors4035
