### ISSUE TITLE
Some player animations get broken, when registered with player_api

### ISSUE THREAD

**Issue by axcore** [minetest-mods/3d_armor#149]
For example, the player will stand on a bed, rather than lying on it (90% of the time).

Here's the broken code, in 3d_armor/init.lua:

```Lua
player_api.register_model("3d_armor_character.b3d", {
	animation_speed = 30,
	textures = {
		armor.default_skin..".png",
		"blank.png",
		"blank.png",
	},
	animations = {
		stand = {x=0, y=79},
		lay = {x=162, y=166},
		walk = {x=168, y=187},
		mine = {x=189, y=198},
		walk_mine = {x=200, y=219},
		sit = {x=81, y=160},
		-- compatibility w/ the emote mod
		wave = {x = 192, y = 196, override_local = true},
		point = {x = 196, y = 196, override_local = true},
		freeze = {x = 205, y = 205, override_local = true},
	},
})
`

Compare the call to the same function, from minetest_game/player_api/init.lua:

`
player_api.register_model("character.b3d", {
	animation_speed = 30,
	textures = {"character.png"},
	animations = {
		-- Standard animations.
		stand     = {x = 0,   y = 79},
		lay       = {x = 162, y = 166, eye_height = 0.3, override_local = true,
			collisionbox = {-0.6, 0.0, -0.6, 0.6, 0.3, 0.6}},
		walk      = {x = 168, y = 187},
		mine      = {x = 189, y = 198},
		walk_mine = {x = 200, y = 219},
		sit       = {x = 81,  y = 160, eye_height = 0.8, override_local = true,
			collisionbox = {-0.3, 0.0, -0.3, 0.3, 1.0, 0.3}}
	},
	collisionbox = {-0.3, 0.0, -0.3, 0.3, 1.7, 0.3},
	stepheight = 0.6,
	eye_height = 1.47,
})
```

Because 3darmor's call to `player_api.register_model()` does not provide values for `.eye_height`, `.stepheight` and `.collisionbox`, the following happens during the call to `player_api.register_model()`:

1. The table is given default values for .eye_height, .stepheight and .collisionbox
2. These values are then copied into each mini-table. Thus, both **stand** and **lay** now have the same value for `.eye_height` (which is obviously wrong)
3. The player_api code notices that most of the animations have the same values, so it maps them onto each other (using the .equals field, in line 42). Thus, most of the animations are now completely wrong

The solution (which I have tested) is to change the table in 3d_armor's call to `player_api.register_model()` so it's the same as player_api's own call to `player_api.register_model()`.

**Comment by SmallJoker** [comment]
@axcore Please confirm whether 082e866 fixed your issue.

**Comment by axcore** [comment]
Confirmed.
