### ISSUE TITLE
3d_armor overrides enable_damage=false

### ISSUE THREAD

**Issue by johalun** [minetest-mods/3d_armor#20]
My server has enable_damage=false but when I enable the 3d_armor mod, the player can die of fall damage. Only the specific 3d_armor mod needs to be enabled, no other mods in the 3d_armor pack.

This only happens when the server is on another computer (same LAN). I can not reproduce it in a local singleplayer world. Server and client are Ubuntu 20.04 with default "apt" install of Minetest 5.1.1.

~~With all other factor kept constant, I bisected the version of 3d_armor and found the following
0.4.0 OK
0.4.4 Players dies~~

**Comment by johalun** [comment]
Scratch that last, the mod didn't load because of missing dependency inventory_plus for 0.4.0. With the dependency loaded, the player still dies of fall damage on 0.4.0

**Comment by BuckarooBanzay** [comment]
> This only happens when the server is on another computer (same LAN). I can not reproduce it in a local singleplayer world. Server and client are Ubuntu 20.04 with default "apt" install of Minetest 5.1.1.

I'm having trouble reproducing this too locally, "stock" minetest with `3d_armor` mod and `damage = false` works for me :confused:
If this really has something to do with network then i guess it would be more of an engine problem, but i'm just guessing here :shrug: 
How did you create the LAN-Setup? With the GUI option?

**Comment by johalun** [comment]
The server runs with the systemd service that comes with the install.

**Comment by BuckarooBanzay** [comment]
> The server runs with the systemd service that comes with the install.

Can you verify that the setting is actually present and false with `/set enable_damage` (you may need the `server` priv)

**Comment by johalun** [comment]
Good news. I did more testing and it seems to be OK in 0.4.14. I'm pretty sure I tried both master and 0.4.14 earlier but maybe I missed something. 
/set enable reports false in 0.4.13 and 0.4.14.
With 0.4.13 I die of fall damage, but latest test show 0.4.14 is OK. 
I stop and start the server between changing versions (using git checkout)

**Comment by johalun** [comment]
Hmm. It's weird.. I stop the server, change from 0.4.13 to 0.4.14, start the server, login and teleport 100 blocks up, fall down and die. However, restarting the server again and keeping 3d_armor at 0.4.14 and I don't die anymore. That's why my earlier test showed that 0.4.14 was also faulty. Maybe the previous mod files are cached or something and wasn't updated by a git checkout until the server was restarted a second time.

**Comment by BuckarooBanzay** [comment]
Uhm, another thing: can you maybe try the `latest` version of the mod?

**Comment by johalun** [comment]
You mean the master branch? That is also OK.

**Comment by BuckarooBanzay** [comment]
> You mean the master branch? That is also OK.

So the bug does only manifest in the _previous_ versions? :confused:

**Comment by johalun** [comment]
It appears so. 0.4.14 and master is OK. 0.4.13 and older has the bug.

**Comment by BuckarooBanzay** [comment]
err, why file the bug then if the newest version works? :roll_eyes:

**Comment by BuckarooBanzay** [comment]
> I was using 0.4.13 at the time. That was what was installed by minetest gui.

Hmm, it should install 0.4.14 though (contentdb: https://content.minetest.net/packages/stu/3d_armor/) don't you see an "update" button somewhere?

**Comment by johalun** [comment]
Nope. Maybe because I'm using Minetest 5.1.1 which is default install on Ubuntu?

**Comment by sirrobzeroone** [comment]
@BuckarooBanzay - One to close?
