### ISSUE TITLE
Divide armor wear amongst number of pieces worn

### ISSUE THREAD

**Issue by sirrobzeroone** [minetest-mods/3d_armor#34]
The partial fix for issue #24 exposed that when armor recieves wear, whether you wear 1 piece or 5 pieces the armor pieces all take the same amount of wear/damage. 

My suggestion; Is that as you wear more pieces of armor the damage/use is spread as a fraction across all armor pieces. Given that damage/use is already set by the armor piece type this would simply involve dividing the use/damage for that armor piece by the number of armor pieces worn. 

I have developed a small change to api.lua>>armor.damage which makes the above change, I have tested this and can't detect any issues - basically replace the current armor.damage starting at ~= line 417 with the below :
```lua
armor.damage = function(self, player, index, stack, use)
	local old_stack = ItemStack(stack)	
	local worn_armor = armor:get_weared_armor_elements(player)               -- Addition Start
	local armor_p_cnt = 0
	for k,v in pairs(worn_armor) do
		armor_p_cnt = armor_p_cnt + 1
	end
	use = math.ceil(use/armor_p_cnt)                                         --Addition End	
	minetest.chat_send_all(stack:get_name().." pre_wear: "..stack:get_wear()) -- Added for testing
	stack:add_wear(use)
	minetest.chat_send_all(stack:get_name().." post_wear: "..stack:get_wear()) -- Added for testing
	self:run_callbacks("on_damage", player, index, stack)
	self:set_inventory_stack(player, index, stack)
	if stack:get_count() == 0 then
		self:run_callbacks("on_unequip", player, index, old_stack)
		self:run_callbacks("on_destroy", player, index, old_stack)
		self:set_player_armor(player)
	end
end
```

Testing and outcomes all as expected - short-hand test cases:

**One**
Wearing just Wooden Chestplate - Recieved full 2000 use/damage

**Two**
Wearing Wooden Chestplate and Wooden Boots - Each Recieved 1000 use/damage

**Three**
Wearing Diamond Chestplate and Wooden Boots - Chestplate 100 use/damage, Boots 1000 use/damage

**Four**
Full Wooden armor Chest, Boots, Leggings, Helmet - Each recieved 500 use/damage

**Five**
Wood Helmet, Diamond Chest, Bronze Leggings, Steel Boots:
Helmet  500 use/damage, Chestplate 50 use/damage, Leggings 100 use/damage, boots 200 use/damage.

I did contemplate making Chestplate take a larger proportion (say 2/6 when wearing 5 pieces ie have chestplate count as "2" not 1) but that makes the fix significantly more complex and I thought for an initial enhancement simple might be best? I'm very happy to take suggestions and ideas and code imporvements etc and even roll in that chestplate fix although I was worried ppl might then not wear chestplates.....

**Comment by sirrobzeroone** [comment]
I did push this issue onto the 3d_armor thread on the minetest forums (https://forum.minetest.net/viewtopic.php?f=11&t=4654&start=850) Fairly sure the regulars would have seen it and flagged any major concerns.

I'll move onto the next step for this for me which is a more intense testing step involving mobs and PVP.  I've also been running the shield fix #30 and haven't noticed any issues, crashes, odd errors etc. So I think I'll just do a single pull request for this and #30 

I  hope I'm not setting a direction here for 3d_armor that was never intended, I'd hate to be standing on anyone's toes.  I'm very much just trying to add functionality/fix issues I'm currently stumbling over that i need in a mod Im working on. I could add this functionality to just my mod but in most cases to me it would appear to be better placed in 3d_armor than in my mod alone.

**Comment by sirrobzeroone** [comment]
Tested so far, with this #30 in place so far

The below in Singleplayer and Server, for the attacks full diamond armor with shield and gloves to push lvl over 100
- Register armor - P
- Put on and take off armor - P
- Mod damage player - P
  - No armor - P
  - under 50 armor - P
  - over 50 armor - P
  - over 110 armor - P
- Mob damage armor - P
  - No armor - P
  - under 50 armor - P
  - over 50 armor - P
  - over 110 armor - P
- Player damage player - P
  - No armor - P
  - under 50 armor - P
  - over 50 armor - P
  - over 110 armor - P
- Player damage armor - P
  - No armor - P
  - under 50 armor - P
  - over 50 armor - P
  - over 110 armor - P
- Player can't damage armor with incorrect weapon level - P
 - Diamond sword on Diamond armor- P
 - Wood sword on Diamond armor - P
- Weapon takes use damage and at correct rate- P
 - Wood sword 10 uses - P
- Craft armor pieces - P
 - Diamond Leggings - P
 - Wood Chestplate - P 

**Still to go**
Inside Protection area
- M vs Pl - expect damage
- M vs Pl armor - expect damage
- Pl vs Pl - expect no damage
- Pl vs Pl armor - expect no damage

Outside Protection area
- M vs Pl - expect damage
- M vs Pl armor - expect damage
- Pl vs Pl - expect damage
- Pl vs Pl armor - expect damage

Mixed armor use testing
- Full Set all the same
- Mixed set Half and Half
- 1 Piece of each

**Comment by BuckarooBanzay** [comment]
fixed by https://github.com/minetest-mods/3d_armor/commit/3ddcbae968c8ad8bf07762d86e6c46bc48fec795

thanks again @sirrobzeroone :+1:
