### ISSUE TITLE
Disable Visuals?

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-mods/3d_armor#46]
Is it possible to disable armor visuals on the character? I want the benefit of wearing armor, but don't want it to cover my custom player skins.

**Comment by BuckarooBanzay** [comment]
> Is it possible to disable armor visuals on the character?

Not yet, no, PR's are accepted but this is a very slim use-case there :thinking: 
Is there a conflict with the player-skins or do you just don't want to obstruct them?

**Comment by AntumDeluge** [comment]
No conflict. My kids just like the character skins, so they're always taking off their armor.

**Comment by BuckarooBanzay** [comment]
i just realized: you could also create a texture-pack where you override the armor-textures with a transparent texture for example, this way the armor is still "on" but not visible :P

**Comment by AntumDeluge** [comment]
Oooh! That's a simple solution. Thanks. :)

**Comment by AntumDeluge** [comment]
Didn't need a texture pack, just needed a setting: #48
