### ISSUE TITLE
API Docs Generation Examples with LDoc & MkDocs

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-mods/3d_armor#54]
As per https://github.com/minetest-mods/3d_armor/pull/51#issuecomment-867321886, I created a couple examples for documenting 3d_armor API with [LDoc](https://stevedonovan.github.io/ldoc/) & [MkDocs](https://www.mkdocs.org/). The documentation is created as an example so is not complete. Keep in mind that I am new to using `MkDocs`, so it could probably look a lot nicer as is done with [Minetest's API](http://minetest.gitlab.io/minetest/).

Examples:
- LDoc:
  - [HTML](https://antummt.github.io/mp-3d_armor/ldoc/docs/)
  - [source file](https://github.com/AntumMT/mp-3d_armor/blob/gh-pages/ldoc/api.ld)
- MkDocs:
  - [HTML](https://antummt.github.io/mp-3d_armor/mkdocs/site/)
  - [source file](https://github.com/AntumMT/mp-3d_armor/blob/gh-pages/mkdocs/docs/index.md)

**Comment by BuckarooBanzay** [comment]
so, from what i can tell: the `mkdocs` variant is built from separate markdown files.
Isn't it better to keep documentation in-line (and as near as possible) with the code like in the `ldoc` example? :thinking:

**Comment by AntumDeluge** [comment]
In the examples I provided, they are actually *both* built from a separate file. However, yes, `LDoc` can parse Lua docstrings from source code which `MkDocs` cannot do (as far as I understand). Currently, `3d_armor` is not using any Lua docstrings (except in the `armor.set_skin_mod` method). So if we use LDoc, we can either use an external file (like in my example), or we can just add docstrings to the code.

**Comment by AntumDeluge** [comment]
I believe that [Doxygen](https://www.doxygen.nl/) has Lua support, or a third party module for Lua support. But LDoc is simpler IMO.

My opinion (with limited knowledge) of the following:
- LDoc: most simple
- MkDocs: best for plain-text readability
- Doxygen: most robust (probably not best for Lua modules)

**Comment by SmallJoker** [comment]
Oh. I did not see this issue. I only check PRs every now and then.
LDoc seems to be more promising, it even has simple [markdown support](https://stevedonovan.github.io/ldoc/manual/doc.md.html#Markdown_Support), which would be great to generate a file for easy lookup online.

**Comment by AntumDeluge** [comment]
@SmallJoker Which would you prefer: Adding Lua docstrings to the code or using a separate file?

**Comment by SmallJoker** [comment]
No idea.

@BuckarooBanzay Which would you prefer: Adding Lua docstrings to the code or using a separate file?

**Comment by BuckarooBanzay** [comment]
> @BuckarooBanzay Which would you prefer: Adding Lua docstrings to the code or using a separate file?

As mentioned above: my money would be on inline-docs, on the code itself

**Comment by AntumDeluge** [comment]
I usually prefer inline as well.

**Comment by AntumDeluge** [comment]
When I get a chance, I will write up some documentation & submit a PR for review.

**Comment by AntumDeluge** [comment]
Started WIP pull request: #58
