### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/3d_armor#63]
There has been no release since 0.4.14 a bit more than a year ago, while I see there were numerous changes.

**Comment by BuckarooBanzay** [comment]
> There has been no release since 0.4.14 a bit more than a year ago, while I see there were numerous changes.

Yes, thats right...

There is no formal release cycle for this mod, do you have suggestions on when to release and what uses does it have?
The `master` branch of this mod is usually "production-ready" :wink:

**Comment by BuckarooBanzay** [comment]
@mckaygerhard please elaborate the :-1: i'm curious ;)

**Comment by SnarkBoojum** [comment]
The use of tagged releases is when a user comes and tells there's a problem, you know if said user runs the last release or some old horse.

That can be as simple as "git tag 20220205" (then later on "git push --tags")

**Comment by mckaygerhard** [comment]
> @mckaygerhard please elaborate the -1 i'm curious ;)

the problems comes when a user has an already working "release" and due you guys just pust to master.. and by example it work for you but not for users THAT PLAYS BETTER THATN yours.. then an update may break all the hole fame.. 

ITS SIMPLE the reason.. of course @BuckarooBanzay  this means that on each release we must wait for at least 4 users that already has the mod strong and widelly used in their servers.. let me guess the response. "this is a open source (not software libre) prohect and we do not have so much time and complicated process" .. 

i also underestood that.. but .. payers need more secure (as in certain target way.. not as security) objetive..

**Comment by mckaygerhard** [comment]
i forgoten.. i have  backported 3d armor for minetest4 cos minetest5 are not widelly played.. sorry guys.. but you must think as player.. not as developer..

**Comment by BuckarooBanzay** [comment]
> the problems comes when a user has an already working "release" and due you guys just pust to master.. and by example it work for you but not for users THAT PLAYS BETTER THATN yours.. then an update may break all the hole fame..

Ok, sure, i guess

> ITS SIMPLE the reason.. of course @BuckarooBanzay this means that on each release we must wait for at least 4 users that already has the mod strong and widelly used in their servers.. let me guess the response. "this is a open source (not software libre) prohect and we do not have so much time and complicated process" ..

Basically this, but as i said: the cdb and at least 2 other public servers track the `master` branch, tagging the releases doesn't change the test-coverage...

> The use of tagged releases is when a user comes and tells there's a problem, you know if said user runs the last release or some old horse.

Git has a commit hash (if you checked it out from there) and the cdb has a release-name (usually YYYY-MM-DD) telling which version you are on shouldn't be a problem IMO

**Comment by mckaygerhard** [comment]
> > ITS SIMPLE the reason.. of course @BuckarooBanzay this means that on each release we must wait for at least 4 users that already has the mod strong and widelly used in their servers.. let me guess the response. "this is a open source (not software libre) prohect and we do not have so much time and complicated process" ..
> 
> Basically this, but as i said: the cdb and at least 2 other public servers track the `master` branch, tagging the releases doesn't change the test-coverage...

test coverage its not the case.. its the most easy way to rollback for admins.. i find a bug in farming of tenplus1 .. to solve i must navigate in a sea of commits until i find the commit.. with tags was more easy, just use the file and that's all puff

> 
> > The use of tagged releases is when a user comes and tells there's a problem, you know if said user runs the last release or some old horse.
> 
> Git has a commit hash (if you checked it out from there) and the cdb has a release-name (usually YYYY-MM-DD) telling which version you are on shouldn't be a problem IMO

usage of commit has is too granular.. as i explain in previous paragraph
