### ISSUE TITLE
Bug fix and Feature

### ISSUE THREAD

**Issue by tenplus1** [minetest-mods/3d_armor#66]
The latest update with nether armor is great but shouldn't that particular armor have fire protection like the crystal set ??

Also in mod.conf nether isn't spelled correctly.

**Comment by BuckarooBanzay** [comment]
> The latest update with nether armor is great but shouldn't that particular armor have fire protection like the crystal set ??

I'm no expert on nether stuff, so i can't really argue about that, if you think it should feel free to make a PR :shrug: 

> Also in mod.conf nether isn't spelled correctly.

Fixed that in 16e264841632a972af48a8834fcacaad1a52008a, thanks :+1:

**Comment by BuckarooBanzay** [comment]
fixed in #67
