### ISSUE TITLE
Player model is incorrect

### ISSUE THREAD

**Issue by IrrlichtMt4** [minetest-mods/3d_armor#74]
The player model is incorrect the body, legs and arms have rectangular pixels instead of square pixels.

**Comment by IrrlichtMt4** [comment]
This is a comparison between the incorrect model and the correct model. 

![screenshot_20220527_184500](https://user-images.githubusercontent.com/102578125/170664987-e280696c-33ff-4c91-ba15-b12360b86e1b.png)

This is the correct model:
![screenshot_20220527_184947](https://user-images.githubusercontent.com/102578125/170665811-c341995c-1faf-4b38-977b-28db43d2d690.png)

**Comment by SmallJoker** [comment]
3d_armor's model must be different to take the armor textures into account. Please propose a corrected model instead. I have no idea how to correct this.

**Comment by IrrlichtMt4** [comment]
Maybe 3d_armor's model could be taken from minetest_game's model and could the extra layer for the armor textures could be added. Sorry, I can't model this in Blender (I'm new to it and I would probably mess a lot of things).

**Comment by IrrlichtMt4** [comment]
An issue in minetest_game exists that could help with modeling at https://github.com/minetest/minetest_game/issues/1411

**Comment by IrrlichtMt4** [comment]
Another solution is to shrink the visuals of the body, arms, and legs while keeping the armor size the same.

**Comment by IrrlichtMt4** [comment]
Another solution is to make the mod look for the already existing model for the player and add the extra layer of armor. Similar to simple_skins when attaching the cape.

**Comment by IrrlichtMt4** [comment]
Here is a model from minetest_game https:github.com/minetest_game/mods/player_api/models/character.blend or see https:github.com/minetest_game/mods/player_api/models/character.b3d .

**Comment by IrrlichtMt4** [comment]
Hello, any comments?

**Comment by IrrlichtMt4** [comment]
Ok got a model (not mine I don't know how to model in Blender so I am giving minetest_game model https://github.com/minetest/minetest_game/tree/master/mods/player_api/models/character.blend .

**Comment by BuckarooBanzay** [comment]
> Ok got a model (not mine I don't know how to model in Blender so I am giving minetest_game model

Yeah, that wont work: the `minetest_game` model doesn't have the shield and armor parts :/

# 3d armor model 
![Screenshot_2022-09-16_10-55-17](https://user-images.githubusercontent.com/39065740/190598975-47270178-d0c2-4cf0-9f5f-5e44a70bd675.png)

# minetest_game model
![Screenshot_2022-09-16_10-55-50](https://user-images.githubusercontent.com/39065740/190598986-1bb0639e-c720-4638-aee3-bde41a61b105.png)

**Comment by IrrlichtMt4** [comment]
Since I can't model the extra armor parts for the player I'm closing this issue. When I can model I will send a model :)

**Comment by IrrlichtMt4** [comment]
How about instead of changing the blender model, we can use a method similar to the visible_sneak mod. Visible sneak makes the player seem slightly squashed when the player sneaks. I think we should use the visible sneak_sneak but not squash the player as much.
