### ISSUE TITLE
could not load smartshop_animation_mask.png

### ISSUE THREAD

**Issue by waxtatect** [minetest-mods/3d_armor#87]
Wield a water/lava source and error message happens 
Perhaps a missing texture?
https://github.com/minetest-mods/3d_armor/blob/7f20e5dcb7711d0e5b1d03a1f22b18890e76b9b8/wieldview/get_texture.lua#L42

**Comment by BuckarooBanzay** [comment]
@fluxionary this looks like a (mistakenly) hardcoded texture from the new wield-algo, right?

**Comment by fluxionary** [comment]
oh, ouch, *that* should not have been included in the code i copied over. i'll add a version of that file for wieldview to use itself.
