### ISSUE TITLE
LICENSE should show current status and year

### ISSUE THREAD

**Issue by Zweihorn** [minetest-mods/3d_armor#93]
Please consider updating the `LICENSE.md` to the current status and team.

Presumably, should read:

Copyright (C) 2013-20**22** Stuart Jones - LGPL v2.1

(or you wait until New Year and make it 2023 already. ;)

Maybe there have been additional contributors? Not sure, if the dev team has to or even wants to be listed. This is totaly at your deliberation, but worth to ask.

**Comment by Zweihorn** [comment]
NB: Certainly it is not me Zweihorn who wants to claim any mentioning here. I was addressing the team of the core developers.

**Comment by Zweihorn** [comment]
Happy New Year!
🍭

**Comment by BuckarooBanzay** [comment]
fixed :+1: 

Stupid question: do we _really_ need that year thing? The timestamps are all in the git history anyway :thinking:

**Comment by Zweihorn** [comment]
> fixed 👍
> 
> Stupid question: do we _really_ need that year thing? The timestamps are all in the git history anyway 🤔

There was never existent a thing called "stupid question". There can only be "stupid answers" or good and bad answers.
⛱️ 

IMO both your deliberation on the fix and the answer 'fixed' were each a good one respectively.

Be reassured, I will not turn into your new year's gnome. To the opposite I am more than flattered by the a.m. and will rest my case indefinitely.

Have fun with MT.

🌻
