### ISSUE TITLE
Error: Not showing ui

### ISSUE THREAD

**Issue by Pantyhose-X** [minetest-mods/3d_armor#99]
https://user-images.githubusercontent.com/42504385/215053080-36e6b4bd-a546-46eb-aa4d-437fb8448447.mp4

**Comment by BuckarooBanzay** [comment]
Please provide more infos about your setup and world, judging from the "texture not found" errors i think the problem might be on your side

**Comment by Pantyhose-X** [comment]
> Please provide more infos about your setup and world, judging from the "texture not found" errors i think the problem might be on your side

Remove minetest.conf, all worlds. Try creating a few more maps and the bug will appear.

Exit the menu, join the world you just created, and the user interface is displayed again.

**Comment by BuckarooBanzay** [comment]
Tested with unified_inventory and 3d_armor on `master`

https://user-images.githubusercontent.com/39065740/215113592-b7c9cdc1-a5e2-4a2a-9ba3-6b2bad4786ac.mp4
